trigger:
  branches:
    include:
      - develop
      - main
      - feature/*
 
pool:
  vmImage: 'ubuntu-latest'
 
steps:
- task: MavenAuthenticate@0
 
- task: Maven@3
  inputs:
    goals: 'clean package'
    options: '-DskipTests=true' # ajusta según política
    mavenPomFile: 'pom.xml'
